### ISSUE TITLE
Pageable tag page problem

### ISSUE THREAD

**Issue by michaelbaudino** [middleman/middleman-blog#108]
Hello,

I'm experiencing a problem when trying to make a tag page pageable: posts don't seem to be in the right order, and I can't browse pages.

Using the following tag page template (Slim):

``` slim

---
pageable: true
per_page: 1

---

h1
  ' Tag page for
  = tagname.capitalize

  - page_articles.each do |article|
      h3== link_to article.title, article.url
      == article.summary

- if paginate
  - if prev_page
    ==' link_to 'Previous page', prev_page, {:class => 'previous-page'}
  - if next_page
    == link_to 'next page', next_page, {:class => 'next-page'}
  .pagination
    ' Page
    =' page_number
    ' of
    =' num_pages
```

The generated tag page displays the last page ("2 of 2") (instead of the first one) and the "Previous page link" doesn't work : it's pointing to the very same tag page (`/posts/tag/some-tag` in my case).

Also, when trying to access directly another page (e.g. `/posts/tag/some-tag/page/1`), i get a 404.

Any idea ?

BTW, here's my middleman-blog config:

``` ruby
activate :blog do |blog|
  blog.prefix = 'posts'
  blog.permalink = ':title'
  blog.default_extension = '.md'
  blog.layout = 'post'
  blog.tag_template = 'tag.html'
  blog.taglink = '/tags/:tag'
  blog.paginate = true
end
```

**Comment by seancdavis** [comment]
I am running into the same situation using html and erb. And I can't update middleman to master because it conflicts with middleman-blog's dependencies.

I added an example that reproduces the errors for me at [https://github.com/seancdavis/middleman-test](https://github.com/seancdavis/middleman-test).

**Comment by seancdavis** [comment]
The issue was related to me removing the `.html` extension from the `blog.taglink` setting. I changed it back to the default:

```ruby
blog.taglink = "tags/{tag}.html"
```

And now it works fine.
