### ISSUE TITLE
localized calendar and tag template generation

### ISSUE THREAD

**Issue by rriemann** [middleman/middleman-blog#180]
How do I configure the blog extension to create calender overviews and tag pages not only for the default language, but also for all other ones?

At the moment I have the impression that this is a still missing feature.

I tried to set `blog.calendar_template = "calendar.:lang.html"` but `:lang` doesn't get resolved.

**Comment by waiting-for-dev** [comment]
As a quick fix while new I18n extension is being developed you can add this in tag and calendar pages:

    <% I18n.locale = articles.first.lang %>
