### ISSUE TITLE
tags produce strange behavior

### ISSUE THREAD

**Issue by rwboyer** [middleman/middleman-blog#189]
Generated tag pages with pagination sometimes fail to produce valid next_page link local vars on first page of multi-page tags even though all pages are generated correctly.

Can be seen with this repo on the first page of localhost/tags/aperture-3/ and localhost/tags/apple-aperture/ as examples.

https://github.com/rwboyer/mm-blog/commits?author=rwboyer

Even though all pages for these tags are built (with correct next_page and prev_page locals) the first page has no next_page var - it is nil.

RB

**Comment by iwarner** [comment]
Is this still an issue - please reply and I will re-open.
