### ISSUE TITLE
Time zone disagreement between "middleman article" and frontmatter

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman-blog#191]
#143 

Seeing an error when running middleman after creating an article:

After typing middleman article "blah" from the command prompt inside my projects directory middleman creates a file with the name `2013-12-30-blah.html.markdown`

Inside 2013-12-30-blah there is the following;

```
---
title: blah
date: 2013-12-30 11:19 EST
tags:
---
```

I'm setting the timezone in my config.rb with the following lines;

``` ruby
require 'tzinfo'
Time.zone = "Australia/Melbourne"
```

The problem seems to be that the date is generated with an EST time zone, when instead it should use whatever the time zone is for "Australia/Melbourne".

**Comment by asecondwill** [comment]
Any resolution for this?
