### ISSUE TITLE
Blog pagination inside a partial?

### ISSUE THREAD

**Issue by SachaG** [middleman/middleman-blog#197]
Is there a way to get pagination to work inside a partial? 

By that I mean that standard pagination code such as:

```
<% if paginate %>
  <p>Page <%= page_number %> of <%= num_pages %></p>
<% end %>
```

works normally inside a blog or tag archive template, but triggers an `undefined local variable or method`page_number'` error if placed inside a partial.

**Comment by tarky** [comment]
Add this above your code in the partial.
```slim
- paginate    = current_page.metadata[:locals]["paginate"]
- num_pages   = current_page.metadata[:locals]["num_pages"]
- page_number = current_page.metadata[:locals]["page_number"]
- prev_page   = current_page.metadata[:locals]["prev_page"]
- next_page   = current_page.metadata[:locals]["next_page"]
```
