### ISSUE TITLE
render blank pages after upgrading middleman to 3.3.2

### ISSUE THREAD

**Issue by kidwm** [middleman/middleman-blog#207]
the repo:
https://github.com/4point/osdc.tw
all blog pages are under /news/ but now get blank content.

**Comment by JTronLabs** [comment]
This is at the top of Google Search results for "middleman blank pages". I was missing a closing `}` at the end of my partial's locals, which was causing a blank page (no crash or error) in Middleman 4.2.0. I upgraded to 4.2.1 and the error was shown.

Example missing brace (after page_articles):

``` erb
<%= partial "partials/post_summaries.erb", locals: {
    articles: page_articles %>
```
