### ISSUE TITLE
Documentation patch

### ISSUE THREAD

**Issue by garthgoldwater** [middleman/middleman-blog#219]
Under custom article collections, at http://middlemanapp.com/basics/blogging/ the documentation should note that:
-- custom collections REQUIRE a template and that 
-- the template must be stored in the /source directory. 

I spent about three hours banging my head against this today.

**Comment by iwarner** [comment]
As far as I work custom collections they always do require a template as below : they can be stored in a folder inside source.

        # Custom collections
        blog.custom_collections = {

            # Category
            category: {
                link:     "#{ path }{category}.html",
                template: "template/category.html"
            },

            # Author
            author: {
                link:     "#{ path }{author}.html",
                template: "template/author.html"
            }

        }
