### ISSUE TITLE
previous_article, next_article wrong results if more articles on same day

### ISSUE THREAD

**Issue by komor72** [middleman/middleman-blog#241]
`previous_article` and `next_article` helpers fail if there are more articles published on the same day, since they look for date less-than or more-than the `current_article`. 
https://github.com/middleman/middleman-blog/blob/master/lib/middleman-blog/blog_article.rb#L210

When I’m looking at the `articles` source code
https://github.com/middleman/middleman-blog/blob/master/lib/middleman-blog/blog_data.rb#L39
and see it sorted I think of another way of finding previous/next, using `index_of` method? I will try to implement it.

**Comment by sarunw** [comment]
Why not putting time in your date? `date: 2015-02-24 16:09 UTC`

**Comment by komor72** [comment]
Brilliant. Confirmed, works. Thanks, @sarunw !
