### ISSUE TITLE
Blog title can't contain question mark(?)

### ISSUE THREAD

**Issue by sarunw** [middleman/middleman-blog#243]
If my title contain question mark I got this error 

```
bad component(expected relative path component)
```

Shouldn't middleman strip it out for me? Or I have to rename file to make this work manually.

**Comment by tdreyno** [comment]
Seems like the slugifier code should strip it out.

**Comment by iwarner** [comment]
Will create some tests for this and re-work the slugifier to remove these.

**Comment by iwarner** [comment]
The actual issue seems to be here - the docs give this example

    parameterized_string.gsub!(/[^a-z0-9\-_]+/i, separator)

We use

    parameterized_string.gsub!(/[^a-z0-9\-_\?]+/, separator)

@tdreyno  why do we not strip out the ? in the slugs?

Something I am missing?

**Comment by iwarner** [comment]
Recoded to this now

Tests pass and ? are stripped from URLs, but not titles

      def safe_parameterize(str)
        parameterized_string = ::ActiveSupport::Inflector.transliterate(str.to_s)
        parameterized_string.parameterize
      end
