### ISSUE TITLE
List ignored posts in "middleman build" output

### ISSUE THREAD

**Issue by hbons** [middleman/middleman-blog#248]
When building, Middleman seems to ignore posts that are in the future. Whilst this is a useful feature, I just spent an hour scratching my head why my post wouldn't build, due to getting the date wrong by a day. There's no way to discover this when you don't know about this feature.

I found this out by stumbling upon this post: https://forum.middlemanapp.com/t/for-some-reason-middleman-is-not-building-pages-for-newly-added-markdown-files/1549. So I'm not the first running into this.

It would be nice if middleman showed the skipped posts (and reason) in the middleman build output.

cc/ @garrett

**Comment by tdreyno** [comment]
Thanks.

**Comment by taf2** [comment]
There should be away to override this feature.   For example, if you wanted to use the blogging feature to support upcoming events list... you would want to build posts for the future.

**Comment by taf2** [comment]
In case anyone else comes to this issue looking for a solution to the same issue here is the solution at least for a events like blog that posts future things:

```
activate :blog do |blog|
  blog.name = "events"
  blog.prefix = "events"
  blog.publish_future_dated = true
end
```

**Comment by iwarner** [comment]
Thanks for adding the context - closing
