### ISSUE TITLE
Activating multiple blogs prevents non-blog pages from working.

### ISSUE THREAD

**Issue by twss** [middleman/middleman-blog#249]
Created a new blog project using `middleman init test --template=blog`, removed the default `activate :blog` from `config.rb` and added:

``` ruby
activate :blog do |blog|
  blog.name = "cats"
  blog.prefix = "cats"
end

activate :blog do |blog|
  blog.name = "dogs"
  blog.prefix = "dogs"
end
```

Created a file `test.html.erb`, containing only:

``` html
<h1><%= "Test" %></h1>
```

When navigating to http://127.0.0.1:4567/test/, I receive the following
#### You must either specify the blog name in calling this method or in your page frontmatter (using the 'blog' blog_name)

```
Ruby    /Users/.../gems/middleman-blog-3.5.3/lib/middleman-blog/helpers.rb: in blog_controller, line 36
Web     GET 127.0.0.1/test.html
```

Clearly, we don't want non-blog content in a blog.

**Comment by tdreyno** [comment]
Is something in your layout expecting blog data?

**Comment by twss** [comment]
Doh! Yes, that. Exactly that!

I'd forgotten to remove the blog-related stuff from the template.

Cheers. Fresh eyes always help. :+1:

**Comment by twss** [comment]
Something else may be amiss in the test suite.

**Comment by iwarner** [comment]
Hiya the whole testing needs looking at as Travis is failing in many areas at the moment. Can you open a new issue regarding the testing please.
