### ISSUE TITLE
Images located with blog posts 

### ISSUE THREAD

**Issue by snewman** [middleman/middleman-blog#252]
I have a problem with my setup. I'm trying to store images alongside my blog posts. Here is my blog config:

```
activate :blog do |blog|
  # set options on blog
  blog.name = "blog"
  blog.prefix = "blog"
  blog.sources =  "{year}/{month}/{day}/{title}"
  blog.permalink = "{year}/{month}/{day}/{title}"
  blog.layout = "blog_post_layout"
  blog.tag_template = "tag.html"
  blog.summary_separator = /READMORE/
  blog.paginate = true
end
```

I'm using pretty URLs too.

My permalinks look like this:

```
/blog/2015/04/07/microservices-for-greenfield/
```

With a directory structure like this:

```
/blog/2015/04/07/microservices-for-greenfield.markdown.erb
/blog/2015/04/07/microservices-for-greenfield.markdown/image.jpg
```

The image displays fine in the blog post. The issue is that the methods to pull back lists of blog posts incorrectly try and pull in images (image.jpg in the above directory example) and process them as text, looking for things like title, date, tag etc.

From digging through the source code it seems that it just blindly pulls back resources from the sitemap, but doesn't do anything to filter out non-textual resources. I can't spot the exact place to make the change, but I think a filter either needs to be applied inside the sitemap or in the appropriate places in blog_data.rb to only select textual resources. I'd take a stab at patching in a fix but before I do that I want to check that I'm not doing something correctly or see if I'm trying to do something that isn't supported right now.

**Comment by ernie** [comment]
OK, so I just found this issue as I was about to give up in trying to find a fix for the same issue on a site I'm working on. @snewman, did you ever work it out? I really don't want to resort to going to .md.erb just to try to write a custom helper to work around this.

Side note: this completely breaks building a static site for me, because the renders happen in the index pages first, which don't work, and get cached. If I comment out the caching code in the render_individual_file method in core extensions, I get a working blog article page, but of course the index pages are still broken.

**Comment by ernie** [comment]
I should probably add that I am following the recommendation at https://middlemanapp.com/basics/blogging/#article-subdirectory for Markdown image format.

**Comment by tdreyno** [comment]
It's pulling back anything that matches:

```
blog.sources =  "{year}/{month}/{day}/{title}"
```

You should make that more specific, for HTML only:

```
blog.sources =  "{year}/{month}/{day}/{title}.html"
```

**Comment by ernie** [comment]
@tdreyno that might be the case for @snewman but it isn't the case with me: My `blog.sources` has the `.html` extension already.

**Comment by ernie** [comment]
@tdreyno A thought: in my case, I am using `blog.prefix = 'blog'` -- is it possible that when it comes to (for instance) `blog/index.html.erb` Middleman is using some other means that is broken, which is treating images, etc as sources?

Or is my issue unrelated to @snewman's after all?

**Comment by ernie** [comment]
So, one last follow-up. It appears that an absolute reference to the source path is properly converted to the destination path no matter where the access occurs from. Doing something like:

`/blog/articles/2015/2015-08-13-article-title/image.png`

behaves as expected, converting to `/blog/2015/08/13/article-title/image.png`. It's only when I use `2015-08-13-article-title/image.png` from the article itself that it breaks rendering from any page but the article page itself.

This lends some credence to my initial suspicion, which was that the relative path from source was being interpreted based on the location of the file currently being rendered, in the case of rendering a collection from an index page. So I did another test, and that appears to be the case. Modifying the image source to:

`articles/2015/2015-08-13-article-title/image.png`

causes the render of source/blog/index.html.erb to reference the image correctly, but breaks the article page.

At this point, I'm going to just work around this by using the absolute source path, but this still seems like a bug -- is there no way to ensure that image references be interpreted from the location of the template they're actually written in, and not from a template that is rendering other templates on a collection?

@tdreyno, I'm sorry if this is less than helpful, but I'm afraid that's all the time I have to troubleshoot this for now. :(

**Comment by ahoward** [comment]
fwiw we use a completely different approach @dojo4 : https://gist.github.com/ahoward/fc5b9bd1fea380b91c71

**Comment by tdreyno** [comment]
Oh, I see your actual issue, @ernie 

Blog "moves" the image assets along to the new article path, but images references in markdown don't point to that new location. I think that's a separate issue. Mind opening a new ticket?

**Comment by ernie** [comment]
Sure thing!
