### ISSUE TITLE
Footnotes not retained in article.summary

### ISSUE THREAD

**Issue by fractaledmind** [middleman/middleman-blog#253]
The `#default_summary_generator` for the `Middleman::Blog::BlogArticle` module improperly handles footnotes in the article body text. If a footnote link exists in the summary text, the current implementation will retain the link in the summary, but without bringing the accompanying footnote content (found at the bottom of the article body). This leaves a dead link in the summary.

This seems the worst of 3 possible implementations:
- strip footnotes from summaries
- retain footnote content along with footnote links in summary
- retain footnote links without content (current implementation)

I'm not certain which **ought** to be the default behavior, but I think the latter is the least helpful. Dead footnote links are gross. If you feel the second option is worth considering, I include below my custom summary generator, which grabs the entire footnote section from an article if any footnotes are in the summary. Would likely be overkill for a default implementation, but I include it just in case it helps:

```
def setup_summary_generator(separator = /(READMORE)/i)
  return Proc.new  do |resource, rendered, length, ellipsis|
    require 'middleman-blog/truncate_html'
    # determine which type of summary to use
    if resource.data.summary?
      summary = resource.data.summary
    elsif rendered =~ separator
      # The separator is found in the text
      summary = rendered.split(separator).first
    elsif length
      summary = TruncateHTML.truncate_html(rendered, length, ellipsis)
    else
      summary = rendered
    end
    # does the summary text include any footnotes?
    if summary.include?('</sup>')
      # find the footnotes div in HTML
      footnote_section = /<div class="footnotes">(.*?)<\/div>/m.match(rendered)
      # if no footnotes, emptry string
      footnotes = if footnote_section.nil? then '' else footnote_section end
      summary = summary + footnotes.to_s
    end
    summary  # return
  end
end
```

**Comment by xavdid** [comment]
Bump, this bug in combination with gjtorikian/html-proofer means that any footnotes you include have to come after your separator or else your build fails (which is a frustrating and fairly arbitrary restriction).

Separately, @smargh, how did you integrate this function into your existing middleman install? Did you just have to edit the gem?

**Comment by iwarner** [comment]
Hiya

Looking through the Features there is a the following :

      activate :blog do |blog|
        blog.summary_generator = Proc.new { "This is my summary, and I like it" }
      end

Creating your own handler for this is whats required. We can look at a way of smartly integrating footnotes later.

@xavdid Would be great to see a repo with what you mean regarding the crash when footnotes are within the summary.

Closing for now - please -reopen a new issue with the crash.
