### ISSUE TITLE
Add a blog_path(name=nil) helper

### ISSUE THREAD

**Issue by paulozoom** [middleman/middleman-blog#254]
There are helpers to link to calendar pages, tag pages, but not the blog index itself.

**Comment by tdreyno** [comment]
I don't think there is a canonical blog path. You could list the full list of posts on any page.

Seems like a better fit for a helper specific to your project:

```
def blog_page
  "/blog/"
end
```

Unless I'm missing something,

**Comment by paulozoom** [comment]
Well, I assumed single or multiple blog configurations with prefixes could use one that would return the prefix used for that particular blog.

But might be a not super-necessary thing and more of a nice to have.

**Comment by tdreyno** [comment]
I'm going to close this, but I totally get your point. I think if we add a "root template" option or something similar to the calendar path options, this would make a lot more sense.

I've posted to twitter to see how many other users have a similar use-case. We'll see.
