### ISSUE TITLE
Customize Tag Slugs

### ISSUE THREAD

**Issue by letunglam** [middleman/middleman-blog#256]
I am using Middleman-Blog and I am quite happy with it. It has only one minor issue that tag slug does not work well with my language (Vietnamese) and this is understandable. I tried to search on Google and this repo to find someone who has same issue but unfortunately I can't find it :(. 

I would like to ask, is there any simple way to customize tag slugs? I just want to replace some characters with another. 

Any help or a simple example would be greatly appreciated.

**Comment by tdreyno** [comment]
I don't think we have any hooks for this right now. But you could override like so:

```
module CustomLink
  def link(original_tag)
    new_tag = original_tag.dup
    # Do something to new_tag to change characters for urls/links 
    super(new_tag)
  end
end

::Middleman::Blog::TagPages.send :include CustomLink
```

**Comment by letunglam** [comment]
@tdreyno Thank you for your help. Could you please let me know where should I put this file?

**Comment by tdreyno** [comment]
`config.rb`

Sorry, that it involves writing a little ruby

**Comment by letunglam** [comment]
@tdreyno Thank you for your help, I am okay with a little ruby writing ruby if this sample work, however I can't make it :(. 

I put your code in `config.rb` and get this error. `config.rb:48:in `block in initialize': uninitialized constant Middleman::Blog::TagPages (NameError)`. Could you please help ?

Again, thank you and I am appreciated it

**Comment by tdreyno** [comment]
Maybe add this up top:

```
require 'middleman-blog/tag_pages'
```

**Comment by letunglam** [comment]
@tdreyno Thank you for your kind help. I am really appreciated it

I used your code and for example I just want to replace all `v` character with `-`. Below is my code

```
require 'middleman-blog/tag_pages'

module CustomLink
  def link(original_tag)
    new_tag = original_tag.dup
    newtag.gsub("v", "-")
    super(new_tag)
  end
end

::Middleman::Blog::TagPages.send :include, CustomLink
```

It doesn't work and I don't know why. Could you please help?

**Comment by tdreyno** [comment]
well, `newtag` should be `new_tag`

```
require 'middleman-blog/tag_pages'

module CustomLink
  def link(original_tag)
    new_tag = original_tag.dup
    new_tag.gsub!("v", "-")
    super(new_tag)
  end
end

::Middleman::Blog::TagPages.send :include, CustomLink
```

**Comment by letunglam** [comment]
@tdreyno Sorry for the typo. I used exact your code and it still doesn't work. Does it work for you ?

**Comment by tdreyno** [comment]
Like I said, you'll have to write some ruby for now. I'm afraid I don't have the time to do it myself.

**Comment by letunglam** [comment]
@tdreyno Thank you for your kind help.
