### ISSUE TITLE
Weekly summary using calendar plugin

### ISSUE THREAD

**Issue by saravanak** [middleman/middleman-blog#257]
I posted this on [Stackoverflow](http://stackoverflow.com/questions/30881244/weekly-summaries-in-middleman), but no response as of now. I am not able to login to the middleman forum, hence posting this here, as this may be tagged as a 'feature'.

This question is related to `middleman-blog`.
I would like to have a weekly summary of the blogs in addition to the year, month and day (optional) templates. I had a look at the `middleman-blog` extensions, which has the `calendar_pages.rb` doing this generation of calendar summaries. 

So the question is, which of the following options is best:
- I go for a "replica" extension which does the same grouping (see https://github.com/middleman/middleman-blog/blob/master/lib/middleman-blog/calendar_pages.rb#L46). This has the disadvantage that the grouping will have to be done twice: once by the calendar pages extension and once by the 'replica' extension **or**
- I write an extension to the `calendar_pages` extension which redefines the `manipulate_resource_list` and friends? **or**
- Take the resource with `page_type` as `year` and iterate through them.But this has a disadvantage that for 'week' to work, the 'year' template should be used by the user. I would want to have the ability to use `week` irrespective of `year` template being used. 

I am in favour of the second approach, since it adds to an existing related functionality. But I am worried by redefinition of methods. Is 'extending' calendar_pages a good practice in ruby?

**Comment by tdreyno** [comment]
I think the replica is the best approach. If you find a lot of overlay, we can move that functionality into a shared location.

**Comment by iwarner** [comment]
@saravanak How did you get on with this? Would be great to see the final code or PR request so we can look at merging.

Please re-open if you can provide.
