### ISSUE TITLE
Access the `blog` method from the config

### ISSUE THREAD

**Issue by fullofcaffeine** [middleman/middleman-blog#258]
I already posted at the middleman forums here: https://forum.middlemanapp.com/t/using-frontmatter-blog-article-data-with-proxy-in-the-config-step/1811 but maybe I didn't explain myself clearly. 

It's quite simple really. I just need access to `blog` at the config step so that I can get the list of articles and then extract the list of categories in order to build a index of posts for each category. Problem is, at this time, `blog` is not available (I haven't looked into the middleman initialization process, but I think the plugin hooks happen after config?) 

There doesn't seem to be a straightforward way to do this without further hacking, am I right?

Thanks in advance.

**Comment by Arcovion** [comment]
As you say, it's just not initialised yet&mdash;you can access it with the `ready` hook:

```ruby
# config.rb
ready do
  p blog
end
```

**Comment by fullofcaffeine** [comment]
Great! Thanks @Arcovion.

**Comment by pomartel** [comment]
Seems like that's no longer working in Middleman v4.
