### ISSUE TITLE
Article summaries and blog.summary.separator producing malformed mark-up

### ISSUE THREAD

**Issue by FearGoidte** [middleman/middleman-blog#265]
I am having trouble generating article summaries using the `blog.summary.separator`. This is my first attempt with Middleman-blog so no doubt it is a simple error on my part. No amount of DuckDuckGoing has helped me.
## Setup

The `blog.summary.separator` is set in `config.rb` as:

``` ruby
blog.summary_separator = /(READMORE)/
```

The article _markdown_ source file text is as follows:

``` markdown
Blog summary

READMORE

First paragraph.
```
## Result

When I use `article.body` this source text generates:

``` xml
<p>Blog summary.</p>

<p></p>

<p>First paragraph.</p>
```

When I use `article.summary` it generates:

``` xml
<p>Blog summary.</p>

<p>
```

If I change the article _markdown_ source file to:

``` markdown
Blog summary
READMORE
First paragraph.
```

Article body:

``` xml
<p>Blog summary. First paragraph.</p>
```

When I use `article.summary` it generates:

``` xml
<p>Blog summary.
```
## Why is it a problem?

I do not want the empty paragraph tag in the article body and as I am serving the built files using the `application/xhtml+xml` media type, I _definitely_ do not want the un-closed paragraph in the article summary.

**Comment by iwarner** [comment]
@FearGoidte Can you confirm the referenced merge fixed your issue - if not please re-open.
