### ISSUE TITLE
middleman-blog ignoring blog.sources?

### ISSUE THREAD

**Issue by douglascamata** [middleman/middleman-blog#266]
Hello, I have the following structure in the extension I'm currently developing:

```
> fixtures/
   |  > basic-multilanguage-blog/
   |  |  > source/
   |  |  |  > articles/
   |  |  |  |  - hello-world.html.markdown
   |  |  |  index.html.erb
   |  |  |  layout.erb
   |  - config.rb
```

This is my `config.rb`:

``` ruby
activate :blog do |blog|
  blog.permalink = ":title.html"
  blog.sources = "articles/:title.html"
end
```

And this is my `index.html.erb`:

``` ruby
<% blog.articles[0...5].each_with_index do |article, i| %>
  <article class="<%= (i == 0) ? 'first' : '' %>">
    <h1><a href="<%= article.url %>"><%= article.title %></a></h1>

    <%= article.summary %>

    <div class="more"><a href="<%= article.url %>">read on &raquo;</a></div>
  </article>
<% end %>
```

And, finally, my `hello-world.html.markdown`:

``` ruby

---
title: Hello World

---

Hello world in en.
```

And this is my feature, modified just to show the index, which is supposed to include my article's title with a link:

``` ruby
Feature: Basic links for post in other language
  Scenario: An english post has a brazilian portuguese version
    Given the Server is running at "basic-multilanguage-blog"
    When I go to "/"
    Then I should see 'Hello World'
```

When I run this feature I get this (among a lot of deprecation warnings from step definitions and rspec expectations):

```
    Then I should see 'foo'                                    # middleman-core-3.4.0/lib/middleman-core/step_definitions/server_steps.rb:94
      expected "" to include "foo" (RSpec::Expectations::ExpectationNotMetError)
      features/basic_links.feature:5:in `Then I should see 'foo''
```

This is really awkward. I already tried to start `middleman server` inside my fixture and inspect the middleman configuration: the blog extension is indeed activated, but I can only access my article using the url `/hello-world.html.markdown` and my `layout.erb` is completely ignored when I do this.

`middleman-core` version is **3.4.0** and `middleman-blog` version is **3.5.4**.

Any ideas?

**Comment by tdreyno** [comment]
Can you try using the `.md` extension?

It seems like you have no markdown engine available. What's your `Gemfile.lock` look like?

**Comment by douglascamata** [comment]
@tdreyno you were right! I was missing a markdown engine. I'm so sorry. :grin:

**Comment by douglascamata** [comment]
@tdreyno Hey, what about showing an error when this happens? My `blog.sources` pointed to a folder with **only** `.html.markdown` files. Maybe `middleman-blog` can identify my intention and throw an error because I don't have a markdown engine installed.

**Comment by tdreyno** [comment]
How is it you managed to not have a markdown engine? One comes stock with Middleman?

**Comment by douglascamata** [comment]
I dunno, @tdreyno. But after I added `kramdown` and `redcarpet` to my `Gemfile` everything was working fine.

**Comment by tdreyno** [comment]
What did you old `Gemfile` look like?

**Comment by douglascamata** [comment]
`middleman-blog` dependency was added in the gem spec and my old `Gemfile` looked like this:

```ruby
gemspec

group :development do
  gem 'rake'
  gem 'rdoc'
  gem 'yard'
end

group :test do
  gem 'cucumber'
  gem 'aruba'
  gem 'rspec'
  gem 'pry'
end
```

**Comment by tdreyno** [comment]
Hmm, so I think blog depends on core, which doesn't include markdown. I'll have to think about that

**Comment by iwarner** [comment]
I think this is more a documentation requirement - or something that is added to the template.

I do see in the blog Gemfile

    gem "kramdown"

    platforms :ruby do
        gem "redcarpet", "~> 3.0"
    end

Maybe added after this ticket - so closing for now - please re-open @douglascamata if still an issue.
