### ISSUE TITLE
warning: duplicated key at line 170 ignored: :lang

### ISSUE THREAD

**Issue by richardkall** [middleman/middleman-blog#269]
- ruby 2.2.4
- middleman 4.0.0
- middleman-blog 4.0.0

When running `middleman server` using i get the following output:

```bash
$HOME/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/middleman-blog-4.0.0/lib/middleman-blog/blog_data.rb:170: warning: duplicated key at line 170 ignored: :lang
```

**Comment by tdreyno** [comment]
Thanks

**Comment by craigmdennis** [comment]
Is this included in a new release yet? I'm still getting this issue with `4.0.0.0`.

**Comment by tdreyno** [comment]
Should be, latest is v4.1.0

**Comment by craigmdennis** [comment]
When it installed to the following: `/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-blog-4.0.0/lib/middleman-blog/blog_data.rb:170: warning: key :lang is duplicated and overwritten on line 170
` indicating it is using `4.0.0`.

I can't see a `4.1` tag in GitHub or [RubyGems](https://rubygems.org/gems/middleman-blog)

**Comment by craigmdennis** [comment]
When explicitly setting `4.1`, bundler response with `Could not find gem 'middleman-blog (~> 4.1)' in any of the gem sources listed in your Gemfile or available on this machine.`

**Comment by tdreyno** [comment]
Ah, whoops, I thought the fix was in core, not blog. You're right, there hasn't been a new release of blog since then

**Comment by sn3p** [comment]
+1 same problem here

**Comment by tdreyno** [comment]
I don't think there is an active blog maintainer right now, so this is not going to get fixed unless someone steps up. I'll ask twitter.

**Comment by FearGoidte** [comment]
I believe this is fixed in the master version. I’m not seeing the error message when loading the gem from the master branch on GitHub.
