### ISSUE TITLE
Date in article path name

### ISSUE THREAD

**Issue by dg-ratiodata** [middleman/middleman-blog#271]
Hi @tdreyno,

is there a good reason to have the date for an article in the path name AND in the front matter? I find it a bit uncomfortable to change them both. Does it makes sense to change the code to just rely on the date from the path OR from the front matter?

Cheers,
Dennis

**Comment by tdreyno** [comment]
You should be able to remove whichever one you don't like. It's intended to be either/or

**Comment by dg-ratiodata** [comment]
#272 is a demonstration what I would like to do.
