### ISSUE TITLE
Duplicated key Warning

### ISSUE THREAD

**Issue by matyus** [middleman/middleman-blog#278]
When I run a middleman server, everything works. However I get this warning:

== The Middleman is loading
/Users/me/.rvm/gems/ruby-2.2.1/gems/middleman-blog-4.0.0/lib/middleman-blog/blog_data.rb:170: warning: duplicated key at line 170 ignored: :lang
== Blog Sources: {year}-{month}-{day}-{title}.html (:prefix + :sources)
== View your site at "http://localhost:4567", "http://127.0.0.1:4567"
== Inspect your site configuration at "http://localhost:4567/__middleman", "http://127.0.0.1:4567/__middleman"

Mac OSX El Capitan 10.11.2

**Comment by tdreyno** [comment]
Fixed in github
