### ISSUE TITLE
Summary with separator broken since #273

### ISSUE THREAD

**Issue by bhollis** [middleman/middleman-blog#279]
PR #273 seems to have fixed summaries in some cases, and broken them in others, in the case where a "more" separator is used. 

1. Summaries are not actually truncating at the separator, instead extending some number of words beyond it. Before, I would reliably get just the text before the separator.
2. If I pass a number in to `summary`, like `summary(250)`, I get the entire post, with no truncation at all.

**Comment by tdreyno** [comment]
Here's a little tweak, it was preferring the separator over the number in some cases.

**Comment by bhollis** [comment]
OK, with that change, the separator doesn't work as I'd expect anymore. It always truncates to the given limit, rather than the limit *only* when there's no separator (which is the old behavior).

As documented:

> The summary for this article, in HTML.
>
> The blog option `summary_generator` can be set to a `Proc` in order to provide custom summary generation. The `Proc` is provided the rendered content of the article (without layout), the desired length to trim the summary to, and the ellipsis string to use. Otherwise the `#default_summary_generator` will be used, which **returns either everything before the summary separator (set via the blog option `summary_separator` and defaulting to "READMORE") if it is found, or the first `summary_length` characters of the post**.


 Here's a contrived example:

Doc:

```markdown
The quick brown fox.

READMORE

Jumped over the lazy dog.
```

Before, if I said `summary(1)`, I'd get "The quick brown fox." because, as an author, I've chosen the summary to be everything before the READMORE marker.

Given this document:

```markdown
The quick brown fox.

Jumped over the lazy dog.
```

Here, if I called `summary(1)`, I'd get just "The", because there's no clear marker for where the summary/intro should be, so I just have to go by the number.

It's true that, before any of these changes, there is no way for me to specify a summary that's *shorter* than the bit before the separator. That would be a nice enhancement. But the behavior as I describe it here is what I intended when I built the functionality the first time.

**Comment by tdreyno** [comment]
Cool. Surprised the tests don't cover this. I'll dive back in. I assumed a value passed to `summary` should override the default behavior.
