### ISSUE TITLE
Newly created site with middleman-blog doesn't generate new posts`

### ISSUE THREAD

**Issue by desireco** [middleman/middleman-blog#281]
I did this on few machines and it seems like it isn't working. 

If I try to generate new post with 
middleman article "A blog post"
Could not find command "article".

this isn't working. Is/Was this obsoleted somehow and still present on Middlemanapp.com site?

In config.rb blog is properly activated, also when I output middleman config, there is no hint of blog.

Please help. Any more info, I am happy to provide.

Middleman 4.1.2 middleman-blog is 4.0.0

**Comment by irisbune** [comment]
Have the same issue

**Comment by desireco** [comment]
I kind of exhausted things to try so any ideas are more then welcome.

**Comment by tdreyno** [comment]
The `article` command was removed. We are planning on bringing it back, but all it really did was create an empty text file in the source folder.

**Comment by desireco** [comment]
That explains it. I honestly would like it, it does create a file with date and all the tags in frontmatter are populated... just nice touch. Thanks I will close this then.

**Comment by tdreyno** [comment]
@desireco Yeah, a lot of people are missing it. It will return, as time allows

**Comment by irisbune** [comment]
If I may kindly suggest: it would help if the documentation on the website is up to date. Middleman Blog's feature was used in our Web Developer's Bootcamp and it didn't leave a good impression when there were errors all around. 
It didn't leave a good impression :(

**Comment by tdreyno** [comment]
PRs welcome

**Comment by khalilgharbaoui** [comment]
@irisbune damn right! tnx for the videos iris :+1:
