### ISSUE TITLE
Blog posts without a title?

### ISSUE THREAD

**Issue by Summonee** [middleman/middleman-blog#282]
Basically, I'm trying to create some blog posts without titles and still have them show up with all the other article, just like what [Manton Reece](http://manton.org/) does with his [microblog](http://www.manton.org/2014/09/defining-a-microblog-post.html). However, whenever I run `middleman build` it comes up with an error for both the post and the index, meaning that neither shows.

Is it possible at all to have a post without the title? I've tried adding `<% if article.title = false %>` to `index.html.erb` but that doesn't seem to work.

Thanks.

**Comment by tdreyno** [comment]
Title are usually used for file naming. But, we might be able to make it work if that's empty.

**Comment by iwarner** [comment]
Hope this is relevant

For one build I use the internal ID of the post

    blog.sources = "/blog/:id.html"

in the frontmatter

    title    :
    date     : 2013/10/13
    slug     : name-here

Worked in server and build

Closing - please re-open if still an issue.
