### ISSUE TITLE
Slashes in blog prefix

### ISSUE THREAD

**Issue by chastell** [middleman/middleman-blog#283]
In Middleman 3 it’s possible to have slashes in blog prefix – e.g., `blog.prefix = '1/125'` – and they work.

In Middleman 4 the support seems to have been lost; `source/1/125/index.html.md` still renders under `/1/125/`, but `source/1/125/2016-03-20-example.md` no longer renders under `/1/125/example/` (this is with `activate :directory_indexes`).

[Here’s](https://github.com/chastell/middleman-1-125-issue) a minimal repro repo: [this commit](https://github.com/chastell/middleman-1-125-issue/tree/d77b971f87e0aac9b2eba38cfa4000435e1c0b7b) works, [this one](https://github.com/chastell/middleman-1-125-issue/tree/a3e66fe3d8227018d81213bcccccee4e08be2a06) does not.

Is this a bug or am I doing something wrong and it worked by accident?

**Comment by tdreyno** [comment]
Thanks for the great bug report. That does look like a bug.

Will take a look as time allows. There's not a lot of available time to focus on blog, with the v4 core requiring much of my attention. Thanks for your patience.

**Comment by chastell** [comment]
> Thanks for the great bug report. That does look like a bug.

Oh good – so I wasn’t breaking any implicit rules/assumptions (or, y’know, basic engineering æsthetics). ;)

(The actual use-case is my [1/125](http://chastell.net/1/125/) photoblog – hence the seemingly unnecessarily fancy blog prefix.)

> Will take a look as time allows.

Sure thing and no worries – this is a super minor issue, probably not affecting anyone else. Thanks so much for Middleman – it’s the bee’s knees!

**Comment by chastell** [comment]
I finally had the chance to debug this, and after a long, stern look it turns out this is most probably not at all a middleman-blog issue, but rather tightening of the filename structure (maybe a tilt 2.0 thingie?) – my use case was broken due to the files being named `2017-01-24-foo.md` rather than `2017-01-24-foo.html.md` (i.e., missing the `.html` part). This worked in Middleman 3 / Tilt 1, but not in Middleman 4 / Tilt 2.

Happily closing this one – thanks so much for all your great work on Middleman! ♥
