### ISSUE TITLE
How do I display two different categories?

### ISSUE THREAD

**Issue by NetOperatorWibby** [middleman/middleman-blog#285]
I've been wracking my brain trying to figure this out and am getting no closer to solutions (I'm also new to Middleman, but all my other pages are working fine).

I basically have a blog that I want to split into two categories: Thoughts and Projects. Blog post tagged with "thoughts" and "projects" would appear in their respective categories. My problem is, I don't where my template folders for those two categories should go, and how to call upon those two pages with pagination.

Can someone point me in the right direction?

**Comment by KitaitiMakoto** [comment]
Hi, @NetOperatorWibby 

What you should do is to set `blog.tag_template` property in your `config.rb`. Documentation on middleman-blog details tag pages: https://middlemanapp.com/basics/blogging/#tags

FYI, my blog configuration might also help you:

* [config.rb][]
* [tag.html][](template for tag pages)
  * Although I show one line with date and title for each article, you can do anything with articles like showing whole body
* [rendered tag page][] as an instance

[config.rb]: https://github.com/KitaitiMakoto/apehuci/blob/091699173f10bc2dd18fa43157abd492ed38f27b/config.rb#L95
[tag.html]: https://github.com/KitaitiMakoto/apehuci/blob/091699173f10bc2dd18fa43157abd492ed38f27b/source/tag.html.erb#L42-L44
[rendered tag page]: http://kitaitimakoto.github.io/apehuci/tags/middleman.html

**Comment by NetOperatorWibby** [comment]
Hi @KitaitiMakoto, thanks for your reply. For some reason, I am unable to achieve the same results. Also, I wanted to be able to visit `/thoughts` and see all of my posts tagged with `thoughts`. The same for `projects`. On your rendered site, going to `/tags` gives me a 404.

I'll keep trying to find solutions.

**Comment by tdreyno** [comment]
There are tests in the repo showing pagination: https://github.com/middleman/middleman/blob/master/middleman-core/features/paginate.feature is a generic fashion (outside of blog)

**Comment by NetOperatorWibby** [comment]
@tdreyno Thanks man, I'll see if I can gleam some ideas from those tests. Would you happen to know how I could get snippets of my posts via my helper? I have no idea how to do that.

**Comment by tdreyno** [comment]
Snippets? If the resources are blog articles, then they will have a `summary` method.

So, `p.summary` in your above example.
