### ISSUE TITLE
Sort posts reverse chronologically, with summaries?

### ISSUE THREAD

**Issue by NetOperatorWibby** [middleman/middleman-blog#286]
Hey everyone!

I am listing my blog posts via categories and it's working well so far. However, my category helper doesn't allow for summaries AND my posts are listed chronologically (I wish to have the latest posts first).

Here is my helper code in my `config.rb`:

```ruby
helpers do
  def pages_by_category(category)
    sitemap.resources.select do |resource|
      resource.data.category == category
    end.sort_by { |resource| resource.data.date }
  end
end
```

This is the code in my view:

```erb
---
layout: default
title: "Thoughts and ramblings"
---

<h1><a href="/thoughts/">Thoughts</a></h1>

<% pages_by_category("thoughts").each do |p| %>
  <section class="thought" role="article">
    <h2><%= link_to p.data.title, p.url %></h2>
    <small class="date"><%= p.data.date.strftime("shared on %B %d, %Y") %></small>

    <p>
      <%= p.data.summary %>
    </p>

    <h3><%= link_to "Read More", p.url %></h3>
  </section>
<% end %>
```

`<%= p.data.summary %>` currently doesn't work, it is just there to show where the post summary would be.

Can anyone point me in the right direction?

**Comment by tdreyno** [comment]
Should be `p.summary`, not `p.data.summary`.

And, simply `.reverse` before `.each` to reverse the array order.

**Comment by NetOperatorWibby** [comment]
@tdreyno The `.reverse` worked, but this is what I get with `p.summary`:

```
NoMethodError at /thoughts/
undefined method `summary' for #<Middleman::Sitemap::Resource:0x007fd8ca6d4b10>
```

**Comment by tdreyno** [comment]
Then it is not an article, which means your selection code might not be correct.

**Comment by NetOperatorWibby** [comment]
I get titles and timestamps though, so it must be something with my helper.

**Comment by tdreyno** [comment]
Resources should return true for this if they are active blog items:

```
resource.is_a?(::Middleman::Blog::BlogArticle)
```

You be using `resource.title` as well (rather than data.title), if it is an article.

**Comment by NetOperatorWibby** [comment]
Am I to put `<%= resource.is_a?(::Middleman::Blog::BlogArticle) %>` in my render code?

**Comment by tdreyno** [comment]
Why aren't you using the normal `blog.articles` helper? Seems like `pages_by_category` might be the source of some of the issues?

**Comment by NetOperatorWibby** [comment]
It definitely is, but when I was attempting to follow the documentation before, nothing was working the way I wanted it, so I found that helper solution.

**Comment by NetOperatorWibby** [comment]
Looking at the docs, I *think* I can find a way to manipulate the sitemap into giving me summaries. Then I can have full control over what I want to output.
