### ISSUE TITLE
Custom Generated Templates

### ISSUE THREAD

**Issue by ericraio** [middleman/middleman-blog#289]
I love that the article command is back, it's such a time saver!
It would be awesome if we could actually supply our own template, what do you guys think?

I'd like to add more to the front matter

Maybe set it in the config file for a article.tt path
https://github.com/middleman/middleman-blog/blob/master/lib/middleman-blog/commands/article.tt

**Comment by FearGoidte** [comment]
Already there:   blog.new_article_template = 'blank-article'
