### ISSUE TITLE
Custom collections hash doesn't respect template path

### ISSUE THREAD

**Issue by dsignr** [middleman/middleman-blog#290]
Inside `config.rb`, I have:

```ruby
  blog.custom_collections = {
    category: {
      link: '/categories/{category}.html',
      template: 'layouts/category/main.html'
    }
  }
```

Doesn't work. I get an error: 
```ruby
/Users/hitman/.rvm/gems/ruby-2.2.3/gems/middleman-core-4.1.1/lib/middleman-core/sitemap/extensions/proxies.rb:86:in `target_resource': Path categories/pioneer.html proxies to unknown file layouts/category/main.html
```
However, if I put the file into the root of the source folder, and set the template path to just `/main.html`, it works.

Any ideas?

Thanks!

**Comment by tdreyno** [comment]
I believe the `layouts` folder is disallowed from having proxy targets. The files in that folder are usually "layout" files which can't render without wrapping another page inside.

**Comment by dsignr** [comment]
Ah, no wonder. Because, I created a different folder with another name and it worked flawlessly. Thanks! Closing this issue.
