### ISSUE TITLE
Accessing the `data` attribute inside helpers.

### ISSUE THREAD

**Issue by dsignr** [middleman/middleman-blog#291]
Consider this example:

There's a data source titled `menu.yml` defined inside the `blog/data` folder:
```yaml
links:
 - Title: Home
 - Title: About
 - Title: Contact
```
Now, I'd like to access this inside of one of my helpers. I have a `menu_helper.rb` defined inside of `blog/helpers` folder:

```ruby
module MenuHelper
 def links
  data.menu.links
 end
end
```
And that throws an 
```ruby 
undefined local variable or method `data' for MenuHelper:Module
```
However, if I remove the module definition and just have this as the contents of my helper file:

```ruby
 def links
  data.menu.links
 end
```
It works flawlessly. Any ideas on how I can access the data attribute inside helpers? 

Thank you, you've been very helpful so far 👍

**Comment by dsignr** [comment]
I figured out the reason the latter works is because when it is directly called in from the views, it can access the data attribute, because in essence you're just calling a function. Whereas, when calling `Module.foo` actually searches for the `data` variable within the scope of the module. This should be common sense and expected, but apparently... .. .. :D

However, I would still like to have the ability to access the data from within the helpers. Right now, in my view `menu.html.erb`, I do something like:

```ruby
<% MenuHelper.set_data(data) %>
```
And in my helper file `blog/helpers/menu_helper.rb`:

```ruby
module MenuHelper
 @data = nil
 def set_data(data)
   @data = data
 end

 def foo
    #Do something with @data
 end
end #End module
```
Obviously, my life would be much simpler if I had access to data within the helpers in the first place :(

Thanks!

**Comment by tdreyno** [comment]
Files in `helpers` are automatically wrapped in an anonymous module and passed to the middleman `helper` command which takes a module and makes it available within a template context. So, simply use the second form in your examples and it will work as expected.

**Comment by dsignr** [comment]
Okay, understood. Thank you! 👍
