### ISSUE TITLE
Article generator running external pipelines

### ISSUE THREAD

**Issue by matthewlehner** [middleman/middleman-blog#292]
Doing some work with Middleman blog today and am running into an issue where running `bundle exec middleman article title` will run the external pipeline I have configured.

I'm not sure if this a configuration thing, or a bug, but can't find anything obvious in the docs/source to figure this out.

Update:

Here's my [config.rb](https://github.com/matthewlehner/matthewlehner.net/blob/9779bdb60bf36e4e1c92ea51e113114060da59c1/config.rb#L43), and I'm using middleman 4.1.7 and middleman-blog 4.0.1

**Comment by tdreyno** [comment]
Hmm, I can see why that is happening. Let me look at fixing.

**Comment by matthewlehner** [comment]
Awesome! Thanks!
