### ISSUE TITLE
Can't create blog

### ISSUE THREAD

**Issue by joeperic** [middleman/middleman-blog#293]
When trying to start a blog, I get the following issue:
[Command line output](https://gist.github.com/joeperic/005c49d38142c4ef60938c3380bcba9a)

I tried to perform a few different things to get certs up to date, but no luck.

Arch Linux - system updated just yesterday
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux] - managed through rvm
Gems:
middleman (4.1.7)
middleman-blog (4.0.1)
middleman-cli (4.1.7)
middleman-core (4.1.7)
middleman-livereload (3.4.6)

All the bundle install/update commands work and update the gems without issue. Other projects on my system have had a similar error and have required me to re-install rubies managed through RVM due to changes in OpenSSL with rubygems. But after re-compiling, all of them are fine.

The cert on directory.middlemanapp.com was issued on Monday, April 18, 2016 at 11:09:00 PM

**Comment by egardner** [comment]
Hi @joeperic – I just ran the same command in an environment using the same version of Ruby (2.2.1p85), and everything built normally. I'm on a Mac and using RBENV, so perhaps the problem has more to do with how Arch and RVM are interacting? Just adding another data point in the hope that this helps.

**Comment by joeperic** [comment]
Thanks. I'll keep chugging along here.

**Comment by joeperic** [comment]
Dirty hack: I copied everything from /etc/ssl/certs/* into ~/.rvm/usr/ssl/certs/ as well as into the /gems/bundler-1.11.2/lib/bundler/ssl_certs/ subdirectory for that rvm-managed version of ruby.

It's all better now!

**Comment by iwarner** [comment]
Seems the issue was fixed closing.
