### ISSUE TITLE
Middleman::Blog::UriTemplates.safe_parameterize breaks with Umlauts and question mark in title

### ISSUE THREAD

**Issue by pfleidi** [middleman/middleman-blog#295]
I've just discovered a weird edge case: When having a blog title with an Umlaut in it that ends with a question mark, the index in `str[i]` doesn't match up.

I'm referring to [this code](https://github.com/middleman/middleman-blog/blob/fea23f9f4b228cd41cd8bfb37ff09c41d7db4b74/lib/middleman-blog/uri_templates.rb#L48-L59):

``` ruby
parameterized_string.chars.to_a.each_with_index do |char, i|
  if char == '?' && str[i].bytes.count != 1
    parameterized_string[i] = str[i]
  end
end
```

As far as I can see: The problem is this: If `str` contains a "ß", it will be translated to "ss" by `transliterate`:

``` ruby
ActiveSupport::Inflector.transliterate('große welt').downcase
=> "grosse welt"
```

Observed behavior: 
- `safe_parameterize` will blow up when the title ends with a question mark
- `safe_parameterize` will ignore any question marks after an umlaut

``` ruby
[1] pry(main)> require 'middleman-blog'
=> true
[2] pry(main)> require 'middleman-blog/uri_templates'
=> true
[3] pry(main)> Middleman::Blog::UriTemplates.safe_parameterize('Hello world')
=> "hello-world"
[4] pry(main)> Middleman::Blog::UriTemplates.safe_parameterize('Große Welt?')
NoMethodError: undefined method `bytes' for nil:NilClass
from /Users/pfleidi/.rvm/gems/ruby-2.2.1/gems/middleman-blog-4.0.1/lib/middleman-blog/uri_templates.rb:56:in `block in safe_parameterize'
[5] pry(main)> Middleman::Blog::UriTemplates.safe_parameterize('Große Welt')
=> "grosse-welt"
[6] pry(main)> Middleman::Blog::UriTemplates.safe_parameterize('Große We?lt')
=> "grosse-we?lt"
```

**Comment by mozz100** [comment]
I've just experienced related issues.  I think it's because ß transliterates to two characters "ss".

The code at https://github.com/middleman/middleman-blog/blob/master/lib/middleman-blog/uri_templates.rb#L56 assumes that `parameterized_string` is the same length as `str`.  This is not necessarily true.  If there are any character like ß and the string ends with a "?" or a character that transliterates to "?", things go wrong.  My example is tændʒoʊ - æ transliterates to "ae"

**Comment by iwarner** [comment]
Hiya

@pfleidi @mozz100 Thanks for the digging

Lets get some Feature tests for this if we can and also a list of characters that transliterate to 2 chars - maybe a reference to a Gem that solves this.

I will create some tests also and see where to fix - any thoughts appreciated on that - PR would be nice.

**Comment by mozz100** [comment]
Alright. I took a look at the specs for this part of the code, and have a fix that seems to work.  I'm using ruby 2.4.0 and following your testing/contributing guides.  Pull request nearly ready...

1. @iwarner could you take a look at https://github.com/mozz100/middleman-blog/blob/bugfix/github-295/spec/uri_templates_spec.rb ?  As I understand things, the '==' operator wasn't actually testing anything.  There's one test (line 82) which is failing.  Previously it was a non-test, but my knowledge of middleman isn't deep enough to know for sure what the expected result should be.

1. @iwarner How *should* safe_parameterize handle question marks?  None of the existing test cases set my expectations.  See line 32 in the same file.

1. Revised code at https://github.com/mozz100/middleman-blog/blob/bugfix/github-295/lib/middleman-blog/uri_templates.rb#L52 handles all the existing test cases and also 'Große Welt?' and 'tændʒoʊ'.  If you can help me with points 1 and 2 I'll try and get a pull request together.

**Comment by iwarner** [comment]
Thanks for this

The safe_parameterize method seems to be used in several places and we have to take note of these to avoid clashes in what the user wants. Would be great to document these and potentially we need to create extra methods to deal with each case.

- Tag naming
- Slugs
- Title into URL

Line 82 is not testing the safe_parameterize but the method extract_directory_path for the creation of an article folder I believe

The question mark issue was fixed but it seems not tested and this is the root of the problem - it is stripped from URLs - but should it be stripped from tags etc. When stripped the char count is modified and then erroring with the multibyte chars

The main thing is to construct the Features at the moment for the testing. And see what else fails with your code submission.

I will be able to help with some of these too but still getting to grips with all the tests as some maybe overlap.

**Comment by iwarner** [comment]
The actual issue seems to be here - the docs give this example

    parameterized_string.gsub!(/[^a-z0-9\-_]+/i, separator)

We use

    parameterized_string.gsub!(/[^a-z0-9\-_\?]+/, separator)

Something I am missing?

Stripping out the Question mark in the slugs gives the desired effect

**Comment by iwarner** [comment]
I have recoded this into :

        parameterized_string = ::ActiveSupport::Inflector.transliterate(str.to_s)
        parameterized_string.parameterize

Seems to work and pass the tests
