### ISSUE TITLE
Blog collections and example - with category

### ISSUE THREAD

**Issue by iwarner** [middleman/middleman-blog#301]
When using the example for Blog collections on this page
https://middlemanapp.com/basics/blogging/

I get the following raised in console and fails on build - is there something in the frontMatter that does not allow the key category: now?

```
Error produced
Template local `category` tried to overwrite an existing context value. Please rename the key when passing to `locals`
```

**Comment by tdreyno** [comment]
We are trying to avoid collisions between `locals` passed into proxies and methods that are built-in helpers. This looks like a bug in blog with that new constraint

**Comment by brodock** [comment]
how to fix this?

**Comment by iwarner** [comment]
@brodock 

I have updated to all the latest and it seems to work - make sure category is in each blog file.

    # Custom collections
    blog.custom_collections = {

        # Category
        category: {
            link:     '/{category}.html',
            template: 'template/category.html'
        }

    }
