### ISSUE TITLE
News feed?

### ISSUE THREAD

**Issue by Jeeppler** [middleman/middleman-blog#302]
does middleman-blog has a helper, extension etc. to create a RSS/ATOM news feed? Is their a way to create a news feed?

**Comment by tdreyno** [comment]
There is one in the blog template: https://github.com/middleman/middleman-templates-blog/blob/master/template/source/feed.xml.builder

**Comment by Jeeppler** [comment]
thanks, works fine. 

What does the .builder extension mean?

**Comment by Jeeppler** [comment]
Where do you get the `xml` object from?

**Comment by tdreyno** [comment]
Builder is a templating language for Ruby which generates XML. It is also where the `xml` comes from.
