### ISSUE TITLE
Use data files as blog posts

### ISSUE THREAD

**Issue by mrh-is** [middleman/middleman-blog#308]
Big picture, I'm trying to use data files as blog posts. To accomplish this, I'm trying to use `proxy` to create pages in the source path of my blog. The pages are created & appear just fine if you navigate directly to them, but they aren't a part of the blog.

I've debugged this to a point where I think that the issue is that the blog is running `manipulate_resource_list` before my proxies get executed, but I'm not sure why that happens, since `proxies` should run before `blog`. I have confirmed that _other_ proxies are indeed called first (including the tag pages ones that this extension sets up), but for some reason not the ones I create in `config.rb`.

**Comment by duboff** [comment]
Hi @mrh-is, having the exact same problem. Have you been able to figure it out?

**Comment by mrh-is** [comment]
Oh, I have! My issue was that my `data` folder was outside my `source` folder. Once I moved it inside, then I could point `blog.sources` at it and everything worked.

**Comment by duboff** [comment]
Isn't the `data` folder supposed to be outside though? Or did you create a separate one (from the main Middleman data folder). Mine is giving me errors when the data folder is moved.

**Comment by mrh-is** [comment]
Mine is quite happy with `data` inside `source`. I'm not sure where it's _supposed_ to be, but I don't get errors. 😕

**Comment by tdreyno** [comment]
Well, it just means that won't be available using the `data` helper... but it doesn't seem like you're using it that way. In your case, the name `data` wouldn't be specific inside `source`. You could call it `blog` or whatever

**Comment by mrh-is** [comment]
Ah, yeah, it looks like we aren't using it for _data_ at all. We should just rename it, good point. So I guess the real solution is just to put the files you want `middleman-blog` to read somewhere under `source`. No other magic necessary.

**Comment by tdreyno** [comment]
👍
