### ISSUE TITLE
Date warning in images (when date set in article frontmatter)

### ISSUE THREAD

**Issue by craigmdennis** [middleman/middleman-blog#310]
I have a date set in my frontmatter file but get the following error on images in a folder named the same as the article file.

``` bash
== Blog Sources: /articles/{title} (:prefix + :sources)
/usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-blog-4.0.1/lib/middleman-blog/blog_article.rb:189:in `date': Blog post articles/the-best-ui-is-no-ui/calendar.png needs a date in its filename or frontmatter (RuntimeError)
```

This is my `config.rb` where I'm calling the blog

``` rb
# Blogging
activate :blog do |blog|
  blog.name = 'articles'
  blog.prefix = "articles"
  blog.sources = "{title}"
  blog.taglink = "categories/{tag}.html"
  blog.permalink = "{title}.html"
  blog.layout = "article"
  blog.paginate = true
  blog.per_page = 10
  blog.page_link = "page:{num}"
  blog.default_extension = ".md"
  blog.generate_day_pages = false
  blog.summary_length = 160
end
```

Middleman 4.1.1
Middleman Blog 4.0.1
Ruby 2.3.0

**Comment by iwarner** [comment]
Hiya

Thanks for this.

There are no Feature tests for this I can see, if you can provide a simple test for your issue please do so. Otherwise I will see what I can dig out.

**Comment by iwarner** [comment]
Hiya

I am closing this issues due to no feedback, please supply the required materials to debug this

Thanks
