### ISSUE TITLE
Tag pages miss articles due to case-sensitiveness

### ISSUE THREAD

**Issue by matiasgarciaisaia** [middleman/middleman-blog#313]
`middleman-blog`'s [BlogData](https://github.com/middleman/middleman-blog/blob/8d093f2/lib/middleman-blog/blog_data.rb#L59-L78) is grouping articles for each tag in a case-sensitive way - ie, `foo` and `Foo` are two different tags.

But [the destination path of the page is case-insensitive](https://github.com/middleman/middleman-blog/blob/8d093f2f8265b5bc44dfc8b54f0037ff331e8c39/lib/middleman-blog/tag_pages.rb#L40-L49) - ie, both `foo` and `Foo` go to `/blog/with-tag/foo.html`.

The result is that you get only one page for those tags (say, just `foo`), but missing the other tag's articles (ie, you don't get the `Foo` articles shown).

I'd expect tags to be case-insensitive - so I'd add `.downcase` in both related snippets. You get a single `foo` tag (that _could_ be shown as `Foo` or not), that shows both `foo` and `Foo` articles. About wether to show `foo` or `Foo` as the tag name, we can use the first/last tag's format - I don't care. If the casing shown isn't the one the user wants, they can always re-tag the articles so it matches.

**Comment by iwarner** [comment]
Hiya @matiasgarciaisaia 

I see what you mean I have replicated this, and I think it makes sense in terms of what you are saying - the other option is to create Tag files that are not case sensitive, but thats a poor option for URL continuity.

Could you please remove the PRs you have done and resubmit a new PR along with a Feature test for this submission.

**Comment by matiasgarciaisaia** [comment]
Ian, I'm actually not keen at all doing feature tests.

I can totally rework the PR, but I'd need your assistance to create the
feature tests. Do you have any test that's too similar to the ones I should
create? Or would it be OK if I give collaborators access to edit my PR so
you can do the tests for me?

Thank you very much

**Comment by iwarner** [comment]
I don't think there are any Fixtures for this - but basically we want to test that Posts tagged with essentially the same word 'Foo' | "foo" bring up the same list of posts on the Tag template. And that these Tags link to the correct template.

Probably add to this set of tests 
https://github.com/middleman/middleman-blog/blob/master/features/tags.feature

Whats the link to your Blog / Repo please?
