### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by axilleas** [middleman/middleman-blog#316]
Hello there! Is it possible to bump the version and include the fix for https://github.com/middleman/middleman-blog/issues/279?

We recently updated to middleman 4.1.10 and it broke our summary separator https://gitlab.com/gitlab-com/www-gitlab-com/issues/796.

Thanks!

**Comment by tdreyno** [comment]
I would suggest pointing Gemfile at the GitHub for now. I'm traveling for work and don't have the time and attention to do a proper release until I get back in a week or so.

**Comment by axilleas** [comment]
@tdreyno that's perfectly fine and that's the route I took :) Just wanted to bring it to your attention, thanks!

**Comment by iwarner** [comment]
I will release a new Gem when 4.0.2 is completed - closing for now.
