### ISSUE TITLE
Custom new article template is relative to middleman-blog source

### ISSUE THREAD

**Issue by weedySeaDragon** [middleman/middleman-blog#319]
The middleman-blog source is hard-coded to be the path for any new article template
[in the `article` command (commands/article.rb)](middleman-blog/lib/middleman-blog/commands/article.rb):

``` ruby
# Template files are relative to this file
      # @return [String]
      def self.source_root
        File.dirname(__FILE__)
      end
. . . 

absolute_article_path = File.join(app.source_dir, article_path + blog_inst.options.default_extension)

template blog_inst.options.new_article_template, absolute_article_path
```

This should be relative to the app directory or else have another option setting for the path to it.

**Comment by jstayton** [comment]
This confused me as well because the [docs](https://middlemanapp.com/basics/blogging/) read:

> If you want to use your own template, you can set `blog.new_article_template` to the path (relative to the project root) of an ERb template that will be used by `middleman article`.

The solution I went with for now is

```ruby
File.expand_path('source/articles/template.erb', __dir__)
```

which expands to an absolute path.

**Comment by iwarner** [comment]
Hiya

I think your work around is acceptable?

Please create a PR or lets debate on the best options for this - config or opinionated default.

**Comment by weedySeaDragon** [comment]
At the very least, the documentation should be changed.  The sentence is confusing and poorly written:

> If you want to use your own template, you can set blog.new_article_template to the path (relative to the project root) of an ERB template that will be used by middleman article. 

How about:

---
You can use your own ERB template for a blog article. In your `config.rb` file, set `blog.new_article_template` to your ERB template path and filename.  Note that the path must be _relative to the project root._

Ex:
```
activate :blog do |blog|
   blog.new_article_template = 'my_templates/my_custom_article_template.tt'
end
```

This will look for your custom template named `my_custom_article_template.tt` in `<project root>/my_templates`.

**Comment by iwarner** [comment]
@weedySeaDragon 

I think your recommendation is spot on.

Would you like to do a PR for middleman guides : https://github.com/middleman/middlemanapp.com

Be a great help to go over that document with your eye and maybe suggest some updates.

Maybe we can replicate this more in a Wiki / or better Readme on this extensions .. thoughts

**Comment by weedySeaDragon** [comment]
I'll do a PR today or tomorrow for this change.

I'll go over the doc for other changes.  (I think there's quite a bit of room for improvement. ahem).  It may be slow,  but I'll keep at it. :-)  

[and so perhaps you can tag this one 'Documentation' as well.]

**Comment by iwarner** [comment]
@weedySeaDragon I am going to create an internal Wiki here also now - to document things in fill - we can then copy snippets over to the master guides when fleshed out

Please do go ahead with this PR though and maybe you can help on the Wiki later
