### ISSUE TITLE
Setting article layout from config doesn't work with HAML?

### ISSUE THREAD

**Issue by corroded** [middleman/middleman-blog#322]
This is just a guess but it does work in html/erb. Currently have HAML as the default templating language and it basically just doesn't honor setting article from the config.

here is my sample config file:

```
# With no layout
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

config[:haml] = {ugly: true, format: :html5}

activate :deploy do |deploy|
  deploy.deploy_method = :git
  deploy.build_before = false
  deploy.host = 'meetmeinouter.space'
  deploy.path = '/'
  deploy.branch = 'master'
  deploy.commit_message = "Deployed at #{Time.now.getlocal} by #{Middleman::Deploy::PACKAGE} #{Middleman::Deploy::VERSION}"
end

activate :directory_indexes
activate :blog do |blog|
  blog.layout = 'article'
  blog.sources = "{category}/{title}.md.markdown"
  blog.permalink = "{category}/{title}/"
end
```

With that, going to a post like `http://10.1.1.59:4567/my_category/yolo` doesn't yield the article layout i have in `source/layouts/article.haml`. BUT if I do:

```
page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false
page "/my_category/*", layout: 'article'
page "/my_category2/*", layout: 'article'
```

it suddenly works? Is this because I'm using HAML? As another observation, tagging also doesn't work with HAML. Like just doing the example:

```
<% blog.tags.each do |tag, articles| %>
    <li>
      <h5><%= tag %></h5>
      <ul>
        <% articles.each do |article| %>
          <li><a href="<%= article.url %>"><%= article.title %></a></li>
        <% end %>
      </ul>
    </li>
  <% end %>
```

(in HAML) doesn't show any article at all.

**Comment by tdreyno** [comment]
Any chance you could provide a test case or a PR with a failing test?

**Comment by corroded** [comment]
@tdreyno I'll try. But I did make a project from scratch with the article tags working, converted the layout to HAML and it broke. I'll see if I can make it into a PR with a failing test. Otherwise I can just link you the repo?

**Comment by iwarner** [comment]
@corroded Please provide the repo - would be cool to get a sense of the Gem version utilised

Put activate :directory_indexes underneath the blog call also - I usually put that last...

**Comment by iwarner** [comment]
Hiya

I am closing this issues due to no feedback, please supply the required materials to debug this

Thanks
