### ISSUE TITLE
Don't want duplicate tags with multiple blogs

### ISSUE THREAD

**Issue by Brixy** [middleman/middleman-blog#323]
Hope, this issue report is not redundant.

I realized that duplicate “virtual” html pages are built, when using the same tag system for multiple blogs.

Therefore, duplicate entries are built—e. g. in a `sitemap.xml` file.

```
activate :blog do |blog|
  blog.name = "blog1"
  blog.tag_template = "tags.html"
  blog.taglink = "tag/:tag.html"
end

activate :blog do |blog|
  blog.name = "blog2"
  blog.tag_template = "tags.html"
  blog.taglink = "tag/:tag.html"
end
```

**Comment by iwarner** [comment]
Hiya

Yeah this is a good edge case - is something you are putting into practice? Usually I would expect a second blog to be isolated in terms of naming....

Can you provide some Feature tests for this and we will put in on the radar.

Thanks

**Comment by Brixy** [comment]
Yes, I am using this scenario in practice.

Both blogs have very large amounts of articles and I want to be able to change the URLs in a batch if needed. That is why categories are not used. Yet, both blogs should share the same tag folder.

Thanks!

**Comment by iwarner** [comment]
Can you show me how you link to the tags please..

i.e. you should be using tag_path( TAG, BLOG_NAME )

http://www.rubydoc.info/github/middleman/middleman-blog/Middleman%2FBlog%2FHelpers%3Atag_path

Can you validate this and see if this fixes this.

**Comment by iwarner** [comment]
Hiya

I am closing this issues due to no feedback, please supply the required materials to debug this

Thanks
