### ISSUE TITLE
Custom URL for posts?

### ISSUE THREAD

**Issue by silasb** [middleman/middleman-blog#328]
I'm trying to get a post to have a custom URL/permalink.  Lets say that I have a blog post titled "Uses" and I want it to be located at `/uses`. I know I could easily create a custom page outside the blog engine, but I want to include comments as well, which means that it makes sense to be a blog post.

I've started hacking on this with custom frontmatter: `permalink: /test` for right now. I've modified some middleman-blog code to make the `article.destination_path` equal to the `permalink` frontmatter.  My sitemap looks like this:

```
Path: blog/2016-12-10-new-use-page-added.html
Build Path: /test/index.html
URL: /test/
Source File: source/blog/2016-12-10-new-use-page-added.html.markdown
Data: {“title"=>"New Use Page Added", "date"=>"2016-12-10 15:37 UTC", "permalink"=>"/test"}
Options: {:lang=>:en}
Locals: lang
```

But when I click the link in the http://localhost:4567/test/ I get 404 not found. So it looks like it's not picking up the new route, but looking through the middleman-blog code I can't figure out how it works. I feel like I'm getting close, but it's not 'clicking.' Any help would be appreciated.

**Comment by silasb** [comment]
Okay, I think I figured it out.  `article.destination_path` can't start with a forward-slash.

Here is my change to handle the `destination_path`

```ruby
if article.data.has_key? 'permalink'
  article.destination_path = ::Middleman::Util.normalize_path article.data['permalink']
else
  article.destination_path = template_path @permalink_template, article
end
```

Does anyone thing this is a good feature to add? I can do a formal PR with tests if needed.

**Comment by iwarner** [comment]
Hiya

Do you know you can include 

    ---
    slug : new-path/to-post
    ---

In the frontmatter

This will override the blog.permalink  = "{category}/{title}.html" from the config.rb.

**Comment by iwarner** [comment]
@silasb Did my post clear this up - closing - please re-open if its still an issue.

**Comment by silasb** [comment]
Haven't had time to check.  I'll look at it next time I get a blog post
ready.

—Silas
