### ISSUE TITLE
Link to n-th page

### ISSUE THREAD

**Issue by Sinetheta** [middleman/middleman-blog#331]
It would be nice to expose links to arbitrary pages, instead of just first, prev, next, and last.

It looks like they're generated here https://github.com/middleman/middleman-blog/blob/master/lib/middleman-blog/paginator.rb#L149

**Comment by iwarner** [comment]
Hiya

Can you give more context to what you want to do here - Utilising the Page_End you should be able to create the missing links you require.

My pagination file is crazy (needs a lot of refactor) but it works 
https://github.com/iwarner/CodeBlender-Middleman/blob/master/source/molecule/pagination/_pagination.haml

Closing please re-open with more context
