### ISSUE TITLE
Filtered articles should not be built

### ISSUE THREAD

**Issue by pomartel** [middleman/middleman-blog#332]
In my `config.rb`, I filter the articles with the `filter` param:

```
activate :blog do |blog|
  blog.filter = proc { |article|
    article.tags.include? target.to_s
  }
end
```

The filter works correctly when building the blog index but all articles are built regardless of the filter. It would be more logical to only build the filtered articles.

**Comment by pomartel** [comment]
As an alternative, I was able to this in Middleman V3:
```
ready do
  blog.articles.each do |article|
    if !article.tags.include?(target.to_s)
      ignore article.path
    end
  end
end
```
But the `blog` variable is no longer accessible from the `config.rb`.

**Comment by iwarner** [comment]
Hiya

You can utilise

    sitemap.resources.select{ | d | d.data.tags ....  }.each do | resource |
    end

in config.rb

Potentially in conjunction with something like

    current_page.is_a? Middleman::Blog::BlogArticle

Not tested but see how that works
I need to investigate the usage for the filter some more

If you can help then please provide some Features / Fixtures tests for this feature

**Comment by pomartel** [comment]
Thanks @iwarner! Your advice worked great and this is what I came up with to ignore all blog posts that don't have a certain tags.
```
ready do
  sitemap.resources.each do | resource |
    if resource.is_a?(Middleman::Blog::BlogArticle) && !resource.data.tags.include?(target.to_s)
      ignore resource.path
    end
  end
end
```
