### ISSUE TITLE
summary_separator doesn't work with /<!-- more -->/

### ISSUE THREAD

**Issue by tonytonyjan** [middleman/middleman-blog#333]
I am sure it worked once, but I can't accurately give you the version number since I've upgrade middleman-blog several times and just found this issue today.

**Comment by iwarner** [comment]
Hiya,

Thanks for sending in the your report. To further aid in finding the issue can you please supply either a full repository that mimics your issue. Or at least a GIST of the config.rb file and an explanation on what steps to take to replicate this

Thank you.

**Comment by iwarner** [comment]
I have just tested this

      # Separator
      blog.summary_separator = //

In blog post - article.html.markdown

Add a separator into the mix into this blog so we can see what \<!-- more --\>happens with the
separator

Output

Summary 
Add a separator into the mix into this blog so we can see what

Can you let me know versions and file names / extensions please
