### ISSUE TITLE
[Feature Request] Article command from source

### ISSUE THREAD

**Issue by xavdid** [middleman/middleman-blog#334]
I usually write blog posts in places besides my site repository. It would be awesome to be able to generate an article using the body of another file. 

For example: `middleman article My Title Here --source ~/writing/posts/my_title_here.md`

This would generate a header from the template and fill the rest of the file with the contents of `my_title_here.md`.

Thanks a bunch!

**Comment by iwarner** [comment]
You could create a Rake / Thor task for this also:

I used something like this a while ago, edit to include it pulling from a source.


    ##
    # Create a new Blog Post
    #
    # @usage $ thor middleman:blogPost
    ##
    desc "blogPost", "Create a New Blog Post"
    method_option :editor, :default => "subl"
    def blogPost( title, date = Time.now.strftime( '%Y-%m-%d' ) )

        path     = "source/blog/"
        title    = title
        filename = path + "#{ date }-#{ title.to_url }.html.haml"

        if File.exist?(filename)
            abort( "#{ filename } already exists!" )
        end

        FileUtils.mkdir path + "#{ date }-#{ title.to_url }"

        puts "Creating new post: #{ filename }"

        open( filename, 'w' ) do | post |

            post.puts "---"
            post.puts "title       : \"#{ title.gsub( /&/, '&amp;' ) }\""
            post.puts "category    :"
            post.puts "subcategory :"
            post.puts "data        :"
            post.puts "developer   :"
            post.puts "publisher   :"
            post.puts "released    :"
            post.puts "tags        :"
            post.puts "---"
            post.puts ""
            post.puts "%h1"
            post.puts "    = data.page.title"

        end

        system( options[ :editor ], filename )

    end

**Comment by xavdid** [comment]
This will probably work, but it would be nice to take advantage of the ability to generate frontmatter and the correct path/filename even if I change it in middleman.

The other option is a shell command that uses `middleman article`, then appends the output of the given file to the newly created one. That's fine, but requires some parsing of the output. I'll look at that though.

**Comment by iwarner** [comment]
Let me know how you get on with the external tasks in this.
