### ISSUE TITLE
Blog not updated for Months

### ISSUE THREAD

**Issue by iwarner** [middleman/middleman-blog#335]
Hiya

Can you please indicate a roadmap for Middleman - the Blog is a massive part of the ecosystem of this product, but it has not been updated for months, and there are many outstanding issues and pull requests.

Would be nice to give the users / community an update on this.

Appreciate everyones efforts with Middleman, but if its no longer being looked after then I need to do due diligence on looking at other products also.

Ian

**Comment by iwarner** [comment]
Message from Thomas

https://github.com/middleman/middleman/issues/1883#issuecomment-278090878

**Comment by nmccrea** [comment]
+1

I am experimenting with Middleman for my next project and so far prefer it over other platforms but since I am building a blog project the lack of activity here is getting me like super down man.
