### ISSUE TITLE
How to disable day_link calendar pages

### ISSUE THREAD

**Issue by JTronLabs** [middleman/middleman-blog#342]
[This thread](https://forum.middlemanapp.com/t/how-to-disable-day-link-day-archive/1546) says to just comment the line out, but that does not work. I want year and month pages to exist but not individual days. Thanks!

**Comment by iwarner** [comment]
The syntax for this is:

    blog.generate_day_pages   = false
    blog.generate_month_pages = false
    blog.generate_year_pages = false

Also if you go to the url /__middleman when you have middleman server up then you can see all the configuration options.

**Comment by JTronLabs** [comment]
Thanks much! I couldn't find this in the documentation and didn't know which options to look for in /__middleman. It's a big help!

**Comment by iwarner** [comment]
@JTronLabs Yeah for context you want to look at the extensions in the confguration and you will see all the blog options.

Good luck.
