### ISSUE TITLE
Unable to activate middleman-blog-4.0.2

### ISSUE THREAD

**Issue by andreamoro** [middleman/middleman-blog#354]
## Actual behaviour
Have been experiencing problems with an existing site, so I decided to create a new one. But by the time I ran the middleman init I got the following error

middleman init
/Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2290:in `raise_if_conflicts': Unable to activate middleman-blog-4.0.2, because middleman-core-3.4.0 conflicts with middleman-core (~> 4.0) (Gem::ConflictError)
from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1410:in `activate'
	from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
	from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
	from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.0/lib/middleman-core/extensions.rb:66:in `block in load_extensions_in_path'
	from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.0/lib/middleman-core/extensions.rb:65:in `each'
	from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.0/lib/middleman-core/extensions.rb:65:in `load_extensions_in_path'
	from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.0/lib/middleman-core/load_paths.rb:39:in `setup_load_paths'
	from /Users/andreamoro/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/middleman-core-3.4.0/bin/middleman:10:in `<top (required)>'
	from /Users/andreamoro/.rbenv/versions/2.4.1/bin/middleman:22:in `load'
	from /Users/andreamoro/.rbenv/versions/2.4.1/bin/middleman:22:in `<main>'

## Additional information

- Ruby version: ruby 2.4.1p111

**Comment by ryanhageman** [comment]
I have the same problem. Had to revert to 3.5.3.
