### ISSUE TITLE
Add more informations in head of article

### ISSUE THREAD

**Issue by hugobarthelemy** [middleman/middleman-blog#356]
Hi everybody !

I love Middleman and I discover Middleman-blog.

I want to use the blog to manage newsletter with several articles for each newsletter.

Is it possible to add keys in the article header (summary, public, city, ...), such as tags?

Thank you for your help

**Comment by iwarner** [comment]
Hi you mean add more Frontmatter to each document

https://middlemanapp.com/basics/frontmatter/

**Comment by hugobarthelemy** [comment]
thank you very much ! :)
