### ISSUE TITLE
Cyrillic tags stopped working in 4.0.2

### ISSUE THREAD

**Issue by konakov** [middleman/middleman-blog#360]
Cyrillic tags stopped working on my blog. They surely did in April, where I wrote the latest post: http://konakov.biz/tags/основы/ (visible in the browser as http://konakov.biz/tags/основы/).
Latin tags work fine.

## Expected behaviour
Blog renders Cyrillic tags like http://konakov.biz/tags/основы/

## Actual behaviour
Blog renders every Cyrillic tag as http://konakov.biz/tags/.html

## Steps to reproduce the problem
https://github.com/konakov/blog

## Additional information
I fixed the problem by downgrading middleman-blog gem to version 4.0.1.

- Ruby version: 2.4.2
- Middleman version: 4.2.1
- Middleman Blog version: 4.0.2
- OS version: Arch Linux current stable

**Comment by Backstabe** [comment]
Problem in Middleman::Blog::UriTemplates.safe_parameterize

2.4.1 :008 > Middleman::Blog::UriTemplates.safe_parameterize('link string')
 => "link-string"
2.4.1 :004 > Middleman::Blog::UriTemplates.safe_parameterize('основы')
 => ""

**Comment by tdreyno** [comment]
Should be fixed in 4.0.3
