### ISSUE TITLE
RuntimeError flag --blog

### ISSUE THREAD

**Issue by nikolaokonesh** [middleman/middleman-blog#367]
why not working?
```
activate :blog do |blog|
  blog.name = "blog"
  blog.prefix = "blog"
  blog.layout = "layouts/post"
  blog.default_extension = ".md"
end
activate :blog do |blog|
  blog.name = "blog2"
  blog.prefix = "blog2"
  blog.layout = "layouts/post"
  blog.default_extension = ".md"
end
```
RuntimeError: You have more than one blog so you must either use the flag --blog (ex. --blog 'myBlog') when calling this method, or add blog: [blog_name] to your page's frontmatter

Help please!!!

**Comment by tdreyno** [comment]
What command are you running?

You may need to set a specific `blog.sources` for each, with different directories for each set of files.
