### ISSUE TITLE
Paginate is showing as false even if set in config.rb to true

### ISSUE THREAD

**Issue by 0foo** [middleman/middleman-blog#385]
##  Expected behavior
With paginate set as true in config.rb it is expected to see the paginate variable set as true in layouts/templates.

paginate set to true: https://github.com/0foo/0foo.dev/blob/master/config.rb#L41

## Actual behaviour

![Screenshot from 2023-07-27 13-45-29](https://github.com/middleman/middleman-blog/assets/6382763/58cac334-634c-4f20-a1dc-875a2a908c0c)

https://github.com/0foo/0foo.dev/blob/master/source/layouts/layout.erb#L17

![Screenshot from 2023-07-27 13-46-45](https://github.com/middleman/middleman-blog/assets/6382763/d32fe350-a527-4e73-bb35-a78fd4477bd5)

https://0foo.dev/

* this autodeploys via netlify

## [Steps to reproduce the problem]

Can just run docker-compose up on this repository.

(https://github.com/0foo/0foo.dev)

- Please provide a repository or some tests we can run through

(https://github.com/0foo/0foo.dev)

* Should just be able to go here and docker-compose up

## Additional information

- Ruby version: 3.2  https://github.com/0foo/0foo.dev/blob/master/Dockerfile#L3
- Middleman version: 4.5.0 https://github.com/0foo/0foo.dev/blob/master/Gemfile.lock#L46
- Middleman Blog version: 4.0.3 https://github.com/0foo/0foo.dev/blob/master/Gemfile.lock#L55
- OS version: 
```
nick@nick-XPS-9315:~$ docker exec -it 638410c7762a /bin/bash
root@638410c7762a:/middleman# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@638410c7762a:/middleman#
```

**Comment by markets** [comment]
Hello @0foo 👋🏼 

I'm helping to maintain this project now, so no, this is not abandoned... but maintaining "large" open source projects for years is hard. This project is more than 12 years old now, so of course there are some legacy code and decisions that will be really hard to understand at this point. That said, I'm still exploring the code, issues, ... but I'll try to do my best (last week I fixed the CI and moved to GH Actions, which a good 1st step).  

Could you please send a failing test or an app that reproduces your error? I'm using this pagination module in a couple of sites with no problems at all.

Best,
Marc

**Comment by 0foo** [comment]
Hey cool! Glad to see this project is still alive.  Its my fav static site generator.

The ticket has a repo with a docker container in it. Should just be able to pull the repo down and docker-compose up.


I couldnt figure it out but I didnt have time to work on it.

**Comment by markets** [comment]
It's still my favorite too 👌 And it's really powerful, you can even write more tools and abstractions on top. I've been building a small framework on top: https://github.com/Subgin/tonic. The combination of Data + Sitemap + configuration as code => super powers 🚀

I already checked those links, but it seems now a Jekyll site.
