### ISSUE TITLE
How can I link to next and previous article?

### ISSUE THREAD

**Issue by renatocarvalho** [middleman/middleman-blog#79]
Hey guys, I'm trying to add a next and prev article navigation functionality to my blog. However I couldn't make it work :( I tried to use `next_article` and `prev_article` but it didn't work.

A screenshot to illustrate what I'm trying to do: http://cl.ly/JdQX

Is it possible to do this with middleman?

**Comment by nedzen** [comment]
:+1:  this is great, exactly what I need, but it doesn't work: this is the error I get : 
> undefined method `previous_article' for nil:NilClass

what can I do ?

**Comment by tdreyno** [comment]
`current_article.previous_article` is `nil`? Seems like you either don't have a previous article from the current one or you are not on an article detail page.

**Comment by nedzen** [comment]
I am on the article page and I have a previous article from the current one. What I try to do is very simple just have homepage, with last article full, and at the end the title of the previous article (linked). and the article page would be exactly the same with the title(linked) at the bottom of the article before it.
I've put this code into my template article like this  `<%=current_article.previous_article%>` and what it returns is just a `#`

**Comment by nedzen** [comment]
so on a fresh install of middleman with the blog and all, I have this at the end of the layout.erb template, at the end of the page and It doesn't work I get syntax error... 
````
  <ul>
    <li>
      <% prev_article = current_article.previous_article %>
        <% if prev_article %>
        <a href="#{prev_article.url}" rel="prev" title="Previous article: #{prev_article.title}"> Previous </a>
    </li>
    <li>
      <% next_article = current_article.next_article %>
        <% if next_article %>
        <a href="#{next_article.url}" rel="next" title="Next article: #{next_article.title}"> Next </a>
    </li>
  </ul>
````

**Comment by tdreyno** [comment]
`if` statements need an `end`

**Comment by nedzen** [comment]
thank you, but still doesn't work, in the page Is generated a "next" link when I click it I see this `http://localhost:4567/2015/03/26/flowers-are-blue/#{next_article.url}` in chrome address bar.

**Comment by AndrewKvalheim** [comment]
I've responded at his [crosspost][post].


[post]: https://forum.middlemanapp.com/t/please-help-i-dont-know-how-to-add-blog-navigation-links-like-this-previous-article-title-next-article-title/1722?u=andrew

**Comment by ChasingUX** [comment]
This no longer seems to work with Middleman 4. Any updates?

**Comment by iwarner** [comment]
@ChasingUX Please open in another thread and post examples.
