### ISSUE TITLE
Middleman build fails when "Middleman article" is used to create article (Timestamp mismatch)

### ISSUE THREAD

**Issue by debajit** [middleman/middleman-blog#94]
Steps to Reproduce:
• Create a blog article using "middleman article title"
• Run middleman build

Expected Results:
The build should not fail.

Actual Results:
The build fails.

Notes:
This is because the markdown filename contains only the date, whereas the frontmatter contains the time as well.
date: 2006-06-10 00:00 +00:00

**Comment by atmosx** [comment]
Hello,

I am moving from Octopress to Middleman. I made a quick script to fix the dates and worked fine for me:

```ruby
require 'fileutils'
require 'time'

files = Dir.glob("*.markdown")
puts "Processing #{files.count} files"
files.each do |f|
  list = []
  list << f
  File.readlines(f).each do |line|
    if line.include?("date: ")
      string = line[6,19]
      string.include?("\n") ? s = string.strip : s = string
      time = Time.parse(string)
      FileUtils.touch f, mtime: time
    end
  end
end
puts "Finished!" 
```

Best regards
